prompts:
  - "A screaming guitarist surrounded by flames, heavy metal concert vibe, ultra-detailed, 4K"
  - "A futuristic cyborg drummer in a post-apocalyptic city, glowing drumsticks, dark lighting"
  - "A skull with glowing red eyes wearing headphones, metallic background, cyber-metal theme"
  - "Band on stage with lightning effects, crowd in silhouette, energy burst, high contrast"
  - "A winged metal angel holding electric guitar, gothic cathedral ruins, night sky"
  - "Floating metallic logo of 'Dasbor Music', surrounded by chains and speakers, dark aura"
